env:
  global:
  - PACKAGE_NAME=Insight2
before_install:
- export BUILD_VERSION=$(date "+%d").$TRAVIS_BUILD_NUMBER
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb
script:
- dpkg-deb --build $PACKAGE_NAME
- mv $PACKAGE_NAME.deb $PACKAGE_NAME_VERSION
after_success:
- ls -l $PACKAGE_NAME_VERSION
- md5sum $PACKAGE_NAME_VERSION
- dpkg --contents $PACKAGE_NAME_VERSION
after_script:
- |
  echo "Uploading package(s) to $FTP_URL ..."
  curl -u $justincletus:$@03Jgabi --ftp-create-dirs -T $PACKAGE_NAME_VERSION ftp://$103.228.112.110/httpdocs/$PACKAGE_NAME_VERSION || DEPLOY_FAILURE=true ;
  if [[ $DEPLOY_FAILURE == 'true' ]]; then echo "Uploading package(s) failed!"; travis_terminate 1; fi;
